theme: jekyll-theme-slate
title: Propuesta Inicial de Contenido
description: Dise침o y Construcci칩n de una Puesta a Tierra para los Laboratorios de Mec치nica Automotriz y Electricidad del ITSMS Basado en la Normativa del Instituto Ecuatoriano de Normalizaci칩n
github:
  is_project_page: false
